# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jt18J6JL5BadANMzN04VxwqHxrepnuvh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
train = pd.read_csv('/content/train_LZdllcl.csv')
test = pd.read_csv('/content/test_2umaH9m (1).csv')
train.head()

test.head(2)

train.info()

test.info()

train.describe()

test.describe()

train.isna().sum()

train[train["education"].isna() == True]

train["education"].fillna(train["education"].mode()[0], inplace=True)
test["education"].fillna(test["education"].mode()[0], inplace=True)

train["previous_year_rating"].fillna(train["previous_year_rating"].median(), inplace=True)
test["previous_year_rating"].fillna(test["previous_year_rating"].median(), inplace=True)

train.info()

test.isna().sum()

train.hist(figsize=(15,15))
plt.show()

sns.countplot(data=train, x="is_promoted")
plt.show()

num_cols = train.select_dtypes("number")
for col in num_cols:
  sns.boxplot(train[col])
  plt.title(col)
  plt.show()

train.select_dtypes("object")

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
cat_cols = ["department",	"education",	"gender"]
num_cols = ["no_of_trainings",	"age",	"previous_year_rating",
            "length_of_service",	"KPIs_met >80%",	"awards_won?",
            	"avg_training_score"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(), cat_cols)
    ]
)

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ))
])

X_train = train.drop("is_promoted", axis=1)
y_train = train["is_promoted"]

X_test = test.copy()

X_train = X_train.drop(["employee_id", "region","recruitment_channel"], axis=1)
X_test = X_test.drop(['recruitment_channel', "region"], axis=1)

y_train

y_train.value_counts()

print(X_train.columns.tolist())

pipe.fit(X_train, y_train)

predictions = pipe.predict(X_train)
predictions

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train, predictions)

print("Train Accuracy:", accuracy)

from sklearn.metrics import classification_report
print(classification_report(y_train, predictions))

#predict test data
predictions = pipe.predict(X_test)
predictions

submission = pd.DataFrame({
    "employee_id": test["employee_id"],
    "is_promoted": predictions
})

submission.to_csv("submission.csv", index=False)

submission

# from sklearn.model_selection import GridSearchCV
# from sklearn.ensemble import RandomForestClassifier
# #RandomForestClassifier estimator= dt
# # Hyperparameter grid
# param_grid = {
#     "n_estimators": [50, 100, 200], #number of decision tree
#     "max_depth": [None, 5, 10, 15],
#     "min_samples_split": [2, 5, 10],
#     "criterion": ["gini"]
# }

# # Grid Search with CV=10
# grid = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=10, scoring="accuracy")
# grid.fit(X_train, y_train)

# best_rf = grid.best_estimator_

# # Train & Test accuracy
# train_acc_tuned_rf= best_rf.score(X_train, y_train)
# print("\nRandom Forest (Tuned)")
# print("Best Params:", grid.best_params_)
# print("Train Accuracy:", train_acc_tuned_rf)